language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8

before_script:
  - python manage.py migrate

script:
  - python manage.py
  - python -m black . --check
  - python -m flake8 --ignore=E303,E501 --max-line-length=88
  - python -m coverage run --source='.' manage.py test

after_success:
  - coveralls